extends: ashare_main_chinext_thsdk_hold_prefer_warm120_dd_light_pos3_base.yaml

project:
  name: ashare_main_chinext_thsdk_hold_prefer_warm120_dd_light_pos3_lossguard5d40_base

strategy:
  rebalance_loss_guard_pct: 0.05
  rebalance_loss_guard_max_days: 40
