extends:
  - base/ashare_main_chinext_thsdk_hold_prefer_warm120_base.yaml
  - base/ashare_main_chinext_thsdk_hold_prefer_dd_guard_base.yaml

project:
  name: ashare_main_chinext_thsdk_hold_prefer_warm120_dd_guard_v1
