extends:
  - custom_watchlist_multifactor_momentum_iter_h_breadth_soft_focus_boost_pos8_nofilter.yaml
  - base/risk_lean_base.yaml

project:
  name: mf_momentum_iter_h_breadth_soft_focus_boost_pos8_nofilter_risk_lean
